version: '3.8'

services:
  # MCP Server
  mcp-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    container_name: energy-analysis-mcp
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/energy_analysis
    volumes:
      - ../data:/app/data
      - ../models:/app/models
      - ../logs:/app/logs
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - energy-network

  # API Server
  api-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    container_name: energy-analysis-api
    ports:
      - "8001:8001"
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/energy_analysis
      - MCP_SERVER_URL=http://mcp-server:8000
    volumes:
      - ../data:/app/data
      - ../models:/app/models
      - ../logs:/app/logs
    depends_on:
      - postgres
      - redis
      - mcp-server
    restart: unless-stopped
    networks:
      - energy-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: energy-analysis-db
    environment:
      - POSTGRES_DB=energy_analysis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - energy-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: energy-analysis-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - energy-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: energy-analysis-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - mcp-server
      - api-server
    restart: unless-stopped
    networks:
      - energy-network

  # Prometheus Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: energy-analysis-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - energy-network

  # Grafana Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: energy-analysis-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - energy-network

  # Data Scheduler
  scheduler:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    container_name: energy-analysis-scheduler
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/energy_analysis
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
    depends_on:
      - postgres
      - redis
    command: ["python", "data_scheduler.py"]
    restart: unless-stopped
    networks:
      - energy-network

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  energy-network:
    driver: bridge
